require("crgwilson.packer")
require("crgwilson.colorscheme")
require("crgwilson.vim-airline")  -- TODO: remove this
require("crgwilson.vim-illuminate")
require("crgwilson.cmp")
require("crgwilson.lsp")
require("crgwilson.ansible-vim")
require("crgwilson.vim-go")
require("crgwilson.nerdtree")
require("crgwilson.sets")
require("crgwilson.keymaps")
require("crgwilson.treesitter")
require("crgwilson.telescope")
