---
- hosts: localhost
  vars:
    username: "{{ ansible_user_id }}"
    user_group: "{{ username }}"

    workspace_user: "{{ username }}"
    workspace_group: "{{ user_group }}"

    user_home: "{{ lookup('ansible.builtin.env', 'HOME') }}"  # /home/cwilson
    user_bin: "{{ lookup('ansible.builtin.env', 'USER_LOCAL_BIN', default='~/.local/bin') }}"  # /home/cwilson/.local/bin
    user_lib: "{{ lookup('ansible.builtin.env', 'USER_LOCAL_LIB', default='~/.local/lib') }}"  # /home/cwilson/.local/lib
    user_opt: "{{ lookup('ansible.builtin.env', 'USER_LOCAL_OPT', default='~/.local/opt') }}"  # /home/cwilson/.local/opt
    user_tmp: "{{ lookup('ansible.builtin.env', 'USER_LOCAL_TMP', default='~/.local/tmp') }}"  # /home/cwilson/.local/tmp
    xdg_data_home: "{{ lookup('ansible.builtin.env', 'XDG_DATA_HOME', default='~/.local/share') }}"  # /home/cwilson/.local/share
    xdg_state_home: "{{ lookup('ansible.builtin.env', 'XDG_STATE_HOME', default='~/.local/state') }}"  # /home/cwilson/.local/state
    xdg_config_home: "{{ lookup('ansible.builtin.env', 'XDG_CONFIG_HOME', default='~/.config') }}"  # /home/cwilson/.config
    xdg_cache_home: "{{ lookup('ansible.builtin.env', 'XDG_CACHE_HOME', default='~/.cache') }}"  # /home/cwilson/.cache
    user_workspace: "{{ user_home }}/workspace"  # /home/cwilson/workspace
    mps_workspace: "{{ user_workspace }}/mps"  # /home/crwilson/workspace/mps
    dashboards_workspace: "{{ user_workspace }}/dashboards"  # /home/cwilson/dashboards
    workspace_dirs:
      - "{{ user_bin }}"
      - "{{ user_lib }}"
      - "{{ user_opt }}"
      - "{{ user_tmp }}"
      - "{{ xdg_data_home }}"
      - "{{ xdg_state_home }}"
      - "{{ xdg_config_home }}"
      - "{{ xdg_cache_home }}"
      - "{{ user_workspace }}"
      - "{{ mps_workspace }}"
      - "{{ dashboards_workspace }}"

    starship_install_prefix: "{{ user_bin }}"
    starship_tmp_dir: "{{ user_tmp }}"
    starship_user: "{{ username }}"
    starship_group: "{{ user_group }}"

    yadm_install_prefix: "{{ user_opt }}"
    yadm_tmp_dir: "{{ user_tmp }}"
    yadm_bin_dir: "{{ user_bin }}"
    yadm_user: "{{ username }}"
    yadm_group: "{{ user_group }}"

    golang_install_prefix: "{{ user_opt }}"
    golang_bin_dir: "{{ user_bin }}"
    golang_tmp_dir: "{{ user_tmp }}"
    golang_user: "{{ username }}"
    golang_group: "{{ user_group }}"

    openjdk_install_prefix: "{{ user_opt }}"
    openjdk_tmp_dir: "{{ user_tmp }}"
    openjdk_user: "{{ username }}"
    openjdk_group: "{{ user_group }}"

    antigen_install_prefix: "{{ xdg_data_home }}"

    git_number_install_prefix: "{{ xdg_data_home }}"
    git_number_bin_dir: "{{ user_bin }}"

    fzf_install_prefix: "{{ user_opt }}"
    fzf_bin_dir: "{{ user_bin }}"

  roles:
    - role: brew
      when: ansible_system == "Darwin"
      tags:
        - brew
    - role: workspace
      tags:
        - workspace
    - role: starship
      tags:
        - starship
    - role: antigen
      tags:
        - antigen
    - role: yadm
      tags:
        - yadm
    - role: golang
      tags:
        - go
    - role: openjdk
      tags:
        - java
    - role: git-number
    - role: fzf
      tags:
        - fzf

  tasks:
    - name: Change my default shell to zsh
      user:
        name: "{{ username }}"
        shell: "/usr/bin/zsh"
      when: username != "runner"

    - name: Install my dotfiles
      yadm:
        repo: git@github.com:crgwilson/all-of-the-dots.git
        dest: "{{ user_home }}"
        update: false
      when: username != "runner"
