---
- src: https://github.com/crgwilson/ansible-role-brew
  version: main
  name: crgwilson.brew

- src: https://github.com/crgwilson/ansible-role-yadm
  version: main
  name: crgwilson.yadm

- src: https://github.com/crgwilson/ansible-role-starship
  version: main
  name: crgwilson.starship

- src: https://github.com/crgwilson/ansible-role-golang
  version: main
  name: crgwilson.golang

- src: https://github.com/crgwilson/ansible-role-git
  version: master
  name: crgwilson.git

- src: https://github.com/crgwilson/ansible-role-pyenv
  version: master
  name: crgwilson.pyenv
