---
name: Test dotfile installer playbook
on:
  pull_request: ~

jobs:
  testit:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
        with:
          path: all-of-the-dots
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: This is dumb
        run: |
          ls -alrt ./all-of-the-dots
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r .local/share/playbook/requirements.txt
      - name: Run ansible
        run: |
          ansible-playbook ./.local/share/playbook/site.yml
